// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ngn_data;

#nullable disable

namespace ngn_data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ngn_DbModels.Models.CallRegister", b =>
                {
                    b.Property<string>("CaseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BSNLContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BSNLContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocketStatusId")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LandlineNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoginTimeHours")
                        .HasColumnType("int");

                    b.Property<int>("LoginTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("NatureOfProblemId")
                        .HasColumnType("int");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CaseId");

                    b.HasIndex("DocketStatusId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NatureOfProblemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SeverityId");

                    b.ToTable("CallRegister");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CallRegisterForOthers", b =>
                {
                    b.Property<string>("CaseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BSNLContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BSNLContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocketStatusId")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LandlineNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoginTimeHours")
                        .HasColumnType("int");

                    b.Property<int>("LoginTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("NatureOfProblenId")
                        .HasColumnType("int");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CaseId");

                    b.HasIndex("DocketStatusId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("CallRegisterForOthers");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CallTypeMaster", b =>
                {
                    b.Property<int>("CallTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallTypeId"));

                    b.Property<string>("CallName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CallTypeId");

                    b.ToTable("CallTypeMaster");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CaseTechnicalComments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SolutionId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalComments")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("TechnicalPersonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TechnicalPersonNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CaseTechnicalComments");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CircleByZoneMaster", b =>
                {
                    b.Property<int>("CircleZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CircleZoneId"));

                    b.Property<string>("CircleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CircleZoneId");

                    b.HasIndex("Zone", "CircleName")
                        .IsUnique();

                    b.ToTable("CircleByZones");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CircleMaster", b =>
                {
                    b.Property<int>("CircleCityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CircleCityId"));

                    b.Property<string>("CircleCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CircleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CircleCityId");

                    b.HasIndex("CircleName");

                    b.HasIndex("CityName");

                    b.HasIndex("CircleCode", "CityCode")
                        .IsUnique();

                    b.ToTable("CircleMaster");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ContactUs", b =>
                {
                    b.Property<int>("ContactUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactUsId"));

                    b.Property<string>("Circle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ContactUsId");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("ngn_DbModels.Models.EquipmentMaster", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EquipmentId");

                    b.HasIndex("ProjectId", "EquipmentName")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ngn_DbModels.Models.EquipmentPartNumber", b =>
                {
                    b.Property<int>("EquipmentPartNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentPartNumberId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EquipmentPartNumberId");

                    b.HasIndex("EquipmentId", "IsActive");

                    b.HasIndex("EquipmentId", "PartNumber")
                        .IsUnique();

                    b.ToTable("EquipmentPartNumbers");
                });

            modelBuilder.Entity("ngn_DbModels.Models.FlashNewsNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsModalAlert")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTicker")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetCircle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartDate", "EndDate");

                    b.ToTable("FlashNewsNotification");
                });

            modelBuilder.Entity("ngn_DbModels.Models.MasterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BSNLContactId")
                        .HasColumnType("int");

                    b.Property<int>("CircleCityId")
                        .HasColumnType("int");

                    b.Property<string>("CityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExchangeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HCLContactId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SSA")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SiteAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SiteName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UTContactId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BSNLContactId");

                    b.HasIndex("CircleCityId");

                    b.HasIndex("HCLContactId");

                    b.HasIndex("UTContactId");

                    b.HasIndex("ProjectId", "CircleCityId");

                    b.ToTable("MasterData");
                });

            modelBuilder.Entity("ngn_DbModels.Models.MasterDatacontact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ContactID");

                    b.ToTable("MasterDatacontact");
                });

            modelBuilder.Entity("ngn_DbModels.Models.NatureOfProblemMaster", b =>
                {
                    b.Property<int>("NatureOfProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NatureOfProblemId"));

                    b.Property<string>("NatureOfProblemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProjectItemId")
                        .HasColumnType("int");

                    b.HasKey("NatureOfProblemId");

                    b.HasIndex("ProjectItemId", "NatureOfProblemName");

                    b.ToTable("NatureOfProblem");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectEmailFeatureMapping", b =>
                {
                    b.Property<int>("ProjectEmailFeatureMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectEmailFeatureMappingId"));

                    b.Property<bool>("IsCallAssignment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCallLogged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRMAInitiated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSLAEscalation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTicketResolvedClosed")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ProjectEmailFeatureMappingId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectEmailFeatureMappings");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectEmailsMaster", b =>
                {
                    b.Property<int>("ProjectEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectEmailId"));

                    b.Property<string>("CCEmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomerEmailOverride")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ToEmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("ProjectEmailId");

                    b.HasIndex("ProjectId", "IsActive");

                    b.ToTable("ProjectEmails");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectGroupMaster", b =>
                {
                    b.Property<int>("ProjectGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectGroupId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectGroupDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProjectGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectGroupId");

                    b.HasIndex("ProjectGroupName")
                        .IsUnique();

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectItemDetails", b =>
                {
                    b.Property<int>("ProjectItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectItemId"));

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectItemId");

                    b.HasIndex("ProjectId", "ItemName");

                    b.ToTable("ProjectItemDetails");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectMaster", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectGroupId");

                    b.HasIndex("ProjectName")
                        .IsUnique();

                    b.ToTable("ProjectMasters");
                });

            modelBuilder.Entity("ngn_DbModels.Models.SeverityMaster", b =>
                {
                    b.Property<int>("SeverityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeverityId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ResolutionSLA")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ResponseSLA")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SeverityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SeverityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeverityId");

                    b.HasIndex("SeverityCode")
                        .IsUnique();

                    b.ToTable("SeverityMasters");
                });

            modelBuilder.Entity("ngn_DbModels.Models.Solution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolutionId"));

                    b.Property<string>("Ageing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSNLCallStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSNLClosedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BSNLClosedHours")
                        .HasColumnType("int");

                    b.Property<int>("BSNLClosedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("BSNLLoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClosedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RMANo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ResolutionTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ResponseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SRNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalPersonComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalPersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalPersonNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SolutionId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("ngn_DbModels.Models.StatusMaster", b =>
                {
                    b.Property<int>("StatusMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusMasterId"));

                    b.Property<string>("BadgeVisualStyle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminalFinalStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ManagementType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusMasterId");

                    b.HasIndex("IsActive");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("StatusMasters");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CallRegister", b =>
                {
                    b.HasOne("ngn_DbModels.Models.StatusMaster", "StatusMaster")
                        .WithMany()
                        .HasForeignKey("DocketStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.EquipmentMaster", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.NatureOfProblemMaster", "NatureOfProblem")
                        .WithMany()
                        .HasForeignKey("NatureOfProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.ProjectMaster", "ProjectMaster")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.SeverityMaster", "SeverityMaster")
                        .WithMany()
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("NatureOfProblem");

                    b.Navigation("ProjectMaster");

                    b.Navigation("SeverityMaster");

                    b.Navigation("StatusMaster");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CallRegisterForOthers", b =>
                {
                    b.HasOne("ngn_DbModels.Models.StatusMaster", "StatusMasterNavId")
                        .WithMany()
                        .HasForeignKey("DocketStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.EquipmentMaster", "EquipmentNavId")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.ProjectMaster", "ProjectNavId")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentNavId");

                    b.Navigation("ProjectNavId");

                    b.Navigation("StatusMasterNavId");
                });

            modelBuilder.Entity("ngn_DbModels.Models.EquipmentMaster", b =>
                {
                    b.HasOne("ngn_DbModels.Models.ProjectMaster", "Project")
                        .WithMany("Equipment")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ngn_DbModels.Models.EquipmentPartNumber", b =>
                {
                    b.HasOne("ngn_DbModels.Models.EquipmentMaster", "Equipment")
                        .WithMany("PartNumbers")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ngn_DbModels.Models.MasterData", b =>
                {
                    b.HasOne("ngn_DbModels.Models.MasterDatacontact", "BSNLContact")
                        .WithMany()
                        .HasForeignKey("BSNLContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ngn_DbModels.Models.CircleMaster", "CircleCity")
                        .WithMany("MasterData")
                        .HasForeignKey("CircleCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.MasterDatacontact", "HCLContact")
                        .WithMany()
                        .HasForeignKey("HCLContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ngn_DbModels.Models.ProjectMaster", "Project")
                        .WithMany("MasterData")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ngn_DbModels.Models.MasterDatacontact", "UTContact")
                        .WithMany()
                        .HasForeignKey("UTContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BSNLContact");

                    b.Navigation("CircleCity");

                    b.Navigation("HCLContact");

                    b.Navigation("Project");

                    b.Navigation("UTContact");
                });

            modelBuilder.Entity("ngn_DbModels.Models.NatureOfProblemMaster", b =>
                {
                    b.HasOne("ngn_DbModels.Models.ProjectItemDetails", "ProjectItem")
                        .WithMany()
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProjectItem");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectEmailFeatureMapping", b =>
                {
                    b.HasOne("ngn_DbModels.Models.ProjectMaster", "Project")
                        .WithMany("EmailFeatureMappings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectEmailsMaster", b =>
                {
                    b.HasOne("ngn_DbModels.Models.ProjectMaster", "Project")
                        .WithMany("ProjectEmails")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectItemDetails", b =>
                {
                    b.HasOne("ngn_DbModels.Models.ProjectMaster", "Project")
                        .WithMany("ProjectItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectMaster", b =>
                {
                    b.HasOne("ngn_DbModels.Models.ProjectGroupMaster", "ProjectGroup")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectGroup");
                });

            modelBuilder.Entity("ngn_DbModels.Models.CircleMaster", b =>
                {
                    b.Navigation("MasterData");
                });

            modelBuilder.Entity("ngn_DbModels.Models.EquipmentMaster", b =>
                {
                    b.Navigation("PartNumbers");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectGroupMaster", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ngn_DbModels.Models.ProjectMaster", b =>
                {
                    b.Navigation("EmailFeatureMappings");

                    b.Navigation("Equipment");

                    b.Navigation("MasterData");

                    b.Navigation("ProjectEmails");

                    b.Navigation("ProjectItems");
                });
#pragma warning restore 612, 618
        }
    }
}
